#!/bin/bash
sleep 3
clear
source code/scripts/variables.sh
source $discl

# Checking if user is root.
###
if [ "$(id -u)" != "0" ]; then
	echo
	echo "This script must be run as root." 1>&2
	echo
	exit 1
fi


# Brief info on script
###
echo "${PURPLE}Valikahn's rtese script${NORMAL}"
echo "Version: $SCRIPTVERSION"
echo "Released: $REVDATE"
echo
echo "This script is for the installation of Apache, PHP, OpenSSL, rtorrent, ruTorrent and Webmin."
echo "There is minimal sections that require user input, if you're here now - you must have read the GitHub readme, lets get this show on the road, shall we?"
echo
echo "${GREEN}Remember to run as root or with sudo.${NORMAL}"
echo
echo "${BOLD}Bugs, feature requests? Visit $GITHUB${NORMAL}"
echo
echo "-------------------------------------------------------------------------------------------"

source $func
source $us_int
