#!/bin/bash
clear
source code/scripts/variables.sh
source $discl

# Checking if user is root.
###
if [ "$(id -u)" != "0" ]; then
	echo
	echo "This script must be run as root." 1>&2
	echo
	exit 1
fi


# Brief info on script
###
echo "${PURPLE}Valikahn's rutorrent-auto-install script${NORMAL}"
echo "Version: $SCRIPTVERSION"
echo "Released: $REVDATE"
echo
echo "${GREEN}Remember to run as root or with sudo.${NORMAL}"
echo
echo "${BOLD}Bugs, feature requests? Visit $GITHUB${NORMAL}"
echo
echo "-------------------------------------------------------------------------------------------"

source $func
source $us_int
