#!/bin/bash
clear

#
# rutorrent-auto - Auto Install Script by Valikahn
#
# Copyright (C) 2020 - 2021 Valikahn <git@insentrica.net>
# Program v0.9-beta - Code Name: PyraFang
# Revision Date - Saturday 30 October 2021 @ 22:10
# Licensed under the GPLv3 License.
#
# Website:  https://www.insentrica.net
# Github:   https://github.com/Valikahn/lamp
# GPLv3 Licence:  https://www.gnu.org/licenses/gpl-3.0.en.html 
#
# This program is free software: 	You can redistribute it and/or modify it under the terms of the GNU General Public License as published by
#									the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#

# Checking if user is root.
###
if [ "$(id -u)" != "0" ]; then
	echo
	echo "This script must be run as root." 1>&2
	echo
	exit 1
fi

# Server IP Address - Ipv4 only
###
	# grep 'inet6' instead of 'inet ' for ipv6
	ip=$(ip addr | grep 'inet ' | awk '{print $2}' | cut -d/ -f1 | grep -v "127." | head -n 1)

# Server Version
###
	# Server version variable
	OS=$(awk '/DISTRIB_ID=/' /etc/*-release | sed 's/DISTRIB_ID=//' | tr '[:upper:]' '[:lower:]')
	ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
	VERSION=$(awk '/DISTRIB_RELEASE=/' /etc/*-release | sed 's/DISTRIB_RELEASE=//' | sed 's/[.]0/./')

	if [ -z "$OS" ]; then
    OS=$(awk '{print $1}' /etc/*-release | tr '[:upper:]' '[:lower:]')
	fi

	if [ -z "$VERSION" ]; then
    VERSION=$(awk '{print $3}' /etc/*-release)
	fi


# Brief info on script
###
echo "Valikahn's rutorrent-auto-install script. Version $SCRIPTVERSION released $REVDATE"
echo
echo "Remember to run as root or with sudo."
echo
echo "Bugs, feature requests? Visit $GITHUB"
echo
echo "-------------------------------------------------------------------------------------------"
echo

# Lets get started
###
echo "Are you happy to proceed? [y,n]"
read val

# did we get an input value?
if [ "$val" == "" ]; then
	clear
	echo "Invalid entry by user...Terminating program..."
	sleep 5
	
# was it a y or a yes?
elif [[ "$val" == "y" ]] || [[ "$val" == "yes" ]]; then

# Updating Packages and Builds
###
clear
echo 'Installing vsftpd'

sudo apt-get -yqq install vsftpd > /dev/null
sudo systemctl start vsftpd
sudo systemctl enable vsftpd
sudo useradd -m $user
#sudo mv /etc/vsftpd.conf /etc/vsftpd.conf.orig
#sudo nano /etc/vsftpd.conf
sudo systemctl restart vsftpd

fi
